name: Go

on:
  push:
    paths: 'userapp/**'
    branches: [ master ]
  pull_request:
    paths: 'userapp/**'
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      
    - name: Build and push
      id: nitinigi2
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: nitinigi2/demo:latest
